import type { Letter } from "./types";

export const diceLetters: Letter[][] = [
  [
    { val: "A", id: "d0-s0", position: null },
    { val: "A", id: "d0-s1", position: null },
    { val: "E", id: "d0-s2", position: null },
    { val: "E", id: "d0-s3", position: null },
    { val: "G", id: "d0-s4", position: null },
    { val: "N", id: "d0-s5", position: null },
  ],
  [
    { val: "A", id: "d1-s0", position: null },
    { val: "A", id: "d1-s1", position: null },
    { val: "C", id: "d1-s2", position: null },
    { val: "E", id: "d1-s3", position: null },
    { val: "I", id: "d1-s4", position: null },
    { val: "O", id: "d1-s5", position: null },
  ],
  [
    { val: "A", id: "d2-s0", position: null },
    { val: "D", id: "d2-s1", position: null },
    { val: "E", id: "d2-s2", position: null },
    { val: "N", id: "d2-s3", position: null },
    { val: "O", id: "d2-s4", position: null },
    { val: "S", id: "d2-s5", position: null },
  ],
  [
    { val: "A", id: "d3-s0", position: null },
    { val: "F", id: "d3-s1", position: null },
    { val: "I", id: "d3-s2", position: null },
    { val: "K", id: "d3-s3", position: null },
    { val: "O", id: "d3-s4", position: null },
    { val: "S", id: "d3-s5", position: null },
  ],
  [
    { val: "A", id: "d4-s0", position: null },
    { val: "I", id: "d4-s1", position: null },
    { val: "M", id: "d4-s2", position: null },
    { val: "N", id: "d4-s3", position: null },
    { val: "O", id: "d4-s4", position: null },
    { val: "R", id: "d4-s5", position: null },
  ],
  [
    { val: "B", id: "d5-s0", position: null },
    { val: "J", id: "d5-s1", position: null },
    { val: "O", id: "d5-s2", position: null },
    { val: "R", id: "d5-s3", position: null },
    { val: "U", id: "d5-s4", position: null },
    { val: "W", id: "d5-s5", position: null },
  ],
  [
    { val: "C", id: "d6-s0", position: null },
    { val: "E", id: "d6-s1", position: null },
    { val: "I", id: "d6-s2", position: null },
    { val: "L", id: "d6-s3", position: null },
    { val: "P", id: "d6-s4", position: null },
    { val: "T", id: "d6-s5", position: null },
  ],
  [
    { val: "C", id: "d7-s0", position: null },
    { val: "H", id: "d7-s1", position: null },
    { val: "I", id: "d7-s2", position: null },
    { val: "O", id: "d7-s3", position: null },
    { val: "S", id: "d7-s4", position: null },
    { val: "T", id: "d7-s5", position: null },
  ],
  [
    { val: "D", id: "d8-s0", position: null },
    { val: "E", id: "d8-s1", position: null },
    { val: "K", id: "d8-s2", position: null },
    { val: "L", id: "d8-s3", position: null },
    { val: "O", id: "d8-s4", position: null },
    { val: "Y", id: "d8-s5", position: null },
  ],
  [
    { val: "D", id: "d9-s0", position: null },
    { val: "E", id: "d9-s1", position: null },
    { val: "N", id: "d9-s2", position: null },
    { val: "R", id: "d9-s3", position: null },
    { val: "S", id: "d9-s4", position: null },
    { val: "Z", id: "d9-s5", position: null },
  ],
  [
    { val: "E", id: "d10-s0", position: null },
    { val: "I", id: "d10-s1", position: null },
    { val: "N", id: "d10-s2", position: null },
    { val: "S", id: "d10-s3", position: null },
    { val: "T", id: "d10-s4", position: null },
    { val: "Y", id: "d10-s5", position: null },
  ],
  [
    { val: "E", id: "d11-s0", position: null },
    { val: "L", id: "d11-s1", position: null },
    { val: "N", id: "d11-s2", position: null },
    { val: "O", id: "d11-s3", position: null },
    { val: "R", id: "d11-s4", position: null },
    { val: "T", id: "d11-s5", position: null },
  ],
  [
    { val: "E", id: "d12-s0", position: null },
    { val: "Ł", id: "d12-s1", position: null },
    { val: "Ó", id: "d12-s2", position: null },
    { val: "Ś", id: "d12-s3", position: null },
    { val: "Ż", id: "d12-s4", position: null },
    { val: "Ź", id: "d12-s5", position: null },
  ],
  [
    { val: "I", id: "d13-s0", position: null },
    { val: "J", id: "d13-s1", position: null },
    { val: "K", id: "d13-s2", position: null },
    { val: "L", id: "d13-s3", position: null },
    { val: "M", id: "d13-s4", position: null },
    { val: "N", id: "d13-s5", position: null },
  ],
  [
    { val: "I", id: "d14-s0", position: null },
    { val: "O", id: "d14-s1", position: null },
    { val: "P", id: "d14-s2", position: null },
    { val: "R", id: "d14-s3", position: null },
    { val: "S", id: "d14-s4", position: null },
    { val: "Z", id: "d14-s5", position: null },
  ],
  [
    { val: "Ą", id: "d15-s0", position: null },
    { val: "Ć", id: "d15-s1", position: null },
    { val: "Ę", id: "d15-s2", position: null },
    { val: "N", id: "d15-s3", position: null },
    { val: "U", id: "d15-s4", position: null },
    { val: "W", id: "d15-s5", position: null },
  ],
] as const;

export const diceWordIndexPattern = [0, 1, 5, 6, 10, 14, 15] as const;

export const GameMode = {
  single: "single",
  hotseat: "hotseat",
  online: "online",
} as const;

export type GameMode = (typeof GameMode)[keyof typeof GameMode];
